### PR TITLE
Npm ready

### PR DESCRIPTION
**Pull request by briangonzalez**

### CODE REVIEW

**Comment by briangonzalez** [comment]
@Anaphase @seanCodes

Can you both give me your NPM usernames and I'll add you on there?

**Comment by briangonzalez** [comment]
The package can be seen here: https://www.npmjs.com/package/jquery.pep.js

**Comment by seanCodes** [comment]
@briangonzalez Thanks, I'm [seancodes](https://www.npmjs.com/~seancodes) on NPM

**Comment by Anaphase** [comment]
I'm [anaphase](https://www.npmjs.com/~anaphase) over there as well!

**Comment by briangonzalez** [comment]
I've gone ahaead and added you both. Feel free to merge and release a new version at will.

Maybe it would be worth it to pow-wow on how to clean up and modernize this repo a bit, if you'd both be interested.

**Comment by seanCodes** [comment]
I'd definitely be interested. I was actually going to ask if you'd be open to bumping the major version to v1 and then starting on a v2 branch with modernized code (drop IE 6 support, use CSS transforms exclusively and deprecate top/left translation, use jQuery 1.8+ for automatic CSS vendor prefixing, etc.)

**Comment by Anaphase** [comment]
I'm unfortunately fairly busy these days so I don't know how much I will be able to help, but I'm more than happy to stick around and just do github admin stuff and whatnot like I have been.

**Pull request merged**
